name: Build and Publish Docker Image

on:
  release:
    types: [created]   # uruchamia po utworzeniu nowego release na GitHubie
  workflow_dispatch:    # pozwala ręcznie wywołać workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t sjuprojekt .

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          docker tag sjuprojekt $IMAGE
          docker push $IMAGE
